//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friends
    {
        public int friendship_id { get; set; }
        public int user_id_1 { get; set; }
        public int user_id_2 { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
