//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int media_id { get; set; }
        public int user_id { get; set; }
        public string file_url { get; set; }
        public string file_type { get; set; }
        public Nullable<System.DateTime> uploaded_at { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
